name: SMT
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - z3-solver
  - tqdm  # se ti serve per logging
  - requests  # se serve, puoi rimuovere se non usato
  - pip:
      - boto==2.49.0  # solo se serve davvero!
